version: '2'
services:
  mysql:
    image: mysql:5.6.34
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev
  app:
    build: .
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - appdata:/workspace
    links:
      - "mysql"
volumes:
  appdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "."